# Generated by Django 6.0.5 on 2026-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_student_enrollment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
